on:
  push:
    branches:
      - main
name: Production Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      # Setup PHP version on server
      - name: Setup PHP
        uses: actions/setup-php@v2
        with:
          php-version: 8.0
          # extensions: imagick, swoole # if project need extensions in future

      # deploy to FTP server
      - name: Deploy files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          FTP_HOST: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21

        # TODO: generate API doc before upload from test
